In [3]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [92]:
a = np.arange(36).reshape(6, 6)
filter = a<18

In [96]:
print('a=>\n{0}'.format(a))

a=>
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [97]:
print('filter=>\n{0}'.format(filter))

filter=>
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [98]:
a[filter] = 0
print('a=>\n{0}'.format(a))

a=>
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
